### ISSUE TITLE
CyaneaContextWrapper getSystemService IllegalStateException

### ISSUE THREAD

**Issue by xDragonZ** [jaredrummler/Cyanea#50]
Could be 💩 firmware related issues.

![image](https://user-images.githubusercontent.com/951083/51438895-3f84b780-1ced-11e9-83b1-a34e205a7a2d.png)

**Model:**
> FL02
> 6045I
> 5015E
> SM-G350E
> VFD 610

**android version:** 6.0 (70%),  4 (13%), 5 (12%), 7 (5%)

```
Fatal Exception: java.lang.IllegalStateException: when (name) {
    LAYOUT…etSystemService(name)
  } must not be null
       at com.jaredrummler.cyanea.inflator.CyaneaContextWrapper.getSystemService(SourceFile:4)
       at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:123)
       at android.app.Activity.getSystemService(Activity.java:5296)
       at android.view.ViewRootImpl.(ViewRootImpl.java:503)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:306)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3347)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2626)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1472)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5743)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

**Comment by inorichi** [comment]
This should be as simple as making [this function nullable](https://github.com/jaredrummler/Cyanea/blob/master/library/src/main/java/com/jaredrummler/cyanea/inflator/CyaneaContextWrapper.kt#L38).
