### ISSUE TITLE
NonSdkApiUsedViolation on API 29+

### ISSUE THREAD

**Issue by gomtos** [jaredrummler/Cyanea#86]
There are so many NonSdkApiUsedViolation on API 29+

In the pre launch report on the play store, I get 'StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation' on a android 9 device test.

On the other devices with lower android version this problem does not occur.

How can I prevent the usage of the non-SDK intefaces so will not get reports of our apps not running or crashing on android 9 devices ?

Logs:

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/LayoutInflater;->mConstructorArgs:[Ljava/lang/Object;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at d.g.b.t.b$a.a(SourceFile:9)
	at d.g.b.q.f$a.onCreateView(SourceFile:7)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:239)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:242)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at d.g.b.q.f.inflate(SourceFile:9)

**Comment by gomtos** [comment]
Is there any problem with the behavior of the utils.Reflection class for StrictMode policy violations in API 28+?
